config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'stickies#month'
  get '' => 'stickies#month', as: :dashboard

  scope module: :account do
    get :settings
    post :settings, action: :update_settings
    get :update_settings, to: redirect('settings')
    patch :change_password
    get :change_password, to: redirect('settings')
  end

  resources :comments do
    collection do
      get :search
    end
  end

  resources :boards do
    member do
      post :archive
    end
    collection do
      post :add_stickies
    end
  end

  scope module: :external do
    get :about
    get '/about/use', action: 'use', as: :about_use
    get :version
  end

  resources :groups

  resources :notifications do
    collection do
      patch :mark_all_as_read
    end
  end

  namespace :project_preferences do
    post :favorite
    post :colorpicker
    patch :update
  end

  resources :project_users do
    member do
      post :resend
    end
    collection do
      get :accept
    end
  end

  get 'invite/:invite_token' => 'project_users#invite'

  resources :projects do
    collection do
      post :selection
    end
    member do
      get :bulk
      post :reassign
    end
  end

  resources :stickies do
    collection do
      get :day
      get :week
      get :month
      get :template
    end
    member do
      post :move
      post :move_to_board
      post :complete
    end
  end

  resources :tags do
    collection do
      post :add_stickies
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :items
      post :selection
    end
    member do
      get :copy
    end
  end

  devise_for :users, path_names: { sign_up: 'join', sign_in: 'login' }, path: ''

  resources :users

  scope module: :internal do
    get :search
    post :update_task_status
    post :toggle_tag_selection
    post :toggle_owner_selection
    post :toggle_project_selection
  end

  get '/day' => 'stickies#day', as: :day
  get '/week' => 'stickies#week', as: :week
  get '/month' => 'stickies#month', as: :month
  get '/tasks' => 'stickies#tasks', as: :tasks
end

app/views/templates/_form.html.haml
= form_for(@template, html: { class: 'form-horizontal' }) do |f|
  - if @template.errors.any?
    .callout.callout-danger
      %strong
        = pluralize @template.errors.count, 'error'
        prohibited this template from being saved

      %ul
        - @template.errors.full_messages.each do |msg|
          %li= msg

  = f.hidden_field :project_id

  .form-group
    = f.label :name, class: 'col-md-2 control-label'
    .col-md-10
      = f.text_field :name, class: 'form-control'

  .form-group
    .col-md-offset-2.col-md-10
      %label.checkbox{ for: 'template_avoid_weekends' }
        = f.check_box :avoid_weekends
        Avoid Weekends
      .callout.callout-info
        %strong What does avoiding weekends do?
        Set this if you prefer tasks to fall during a weekday. Saturday tasks get pushed back to Friday and Sunday tasks get pushed forward to Monday.

  #items_container{ data: { object: 'sortable' } }
    = render 'items'

  .form-group
    .col-md-offset-2.col-md-10
      %label.control-label
        = link_to 'Add Another Task', '#', id: 'add_more_items', class: 'btn btn-xs btn-default'

  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      = cancel

app/views/templates/_items.html.haml
- if @template.template_items.size == 0
  - template_item = @template.template_items.new(description: '')
  = render 'template_items/form', template_item: template_item
- else
  - @template.template_items.each do |template_item|
    = render 'template_items/form', template_item: template_item

app/views/templates/_templates.html.haml
= render 'layouts/per_page', per_page: 40, object_count: @templates.total_count

%table.table
  %col{ width: '10%' }
  %col{ width: '10%' }
  %col{ width: '80%' }
  %col{ width: '1%' }
  %thead
    %tr
      = th_sort_field @order, 'templates.name', 'Name'
      %th Project
      %th Items
      %th Actions

  - @templates.each do |template|
    %tr
      %td= link_to template.name, template
      %td= link_to template.project.name, template.project
      %td{ style: 'background-color:white' }
        = render 'template_items/index', template: template
      %td.nowrap
        - if current_user.all_templates.include?(template)
          = link_to 'Edit', edit_template_path(template), class: 'btn btn-xs btn-default'
          = link_to 'Delete', template, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Template #{template.name}?" }

.center= paginate @templates, theme: 'bootstrap'

app/views/templates/edit.html.haml
- @title = "Edit Template #{@template.name_was}"

.page-header
  %h1
    - if @template.project
      = link_to @template.project.name, @template.project
      &middot;
    = link_to 'Templates', templates_path(project_id: @template.project_id)
    &middot;
    = link_to @template.name, @template
    &middot; Edit

= render 'form'

app/views/templates/index.html.haml
- @title = 'Templates'
.page-header
  %h1
    -# TODO: Check if templates always have projects or not.
    - if @project
      = link_to @project.name, @project
      &middot;
    = @title
    = link_to 'Create Template', new_template_path(template: { project_id: @project.id }), class: 'btn btn-xs btn-primary' if @project

= form_tag templates_path, method: :get, class: 'form-inline' do
  = hidden_field_tag :order, params[:order]
  = hidden_field_tag :project_id, params[:project_id]
  = text_field_tag 'search', params[:search], class: 'form-control'
  = submit_tag 'Search', class: 'btn btn-primary'
  = link_to 'Reset', templates_path( project_id: (@project ? @project.id : nil) ), class: 'btn btn-default'

= render 'templates/templates'

app/views/templates/items.js.erb
$('#items_container').html("<%=j render 'items' %>");

app/views/templates/new.html.haml
- @title = 'New Template'

.page-header
  %h1
    - if @template.project
      = link_to @template.project.name, @template.project
      &middot;
    = link_to 'Templates', templates_path(project_id: @template.project_id)
    &middot;
    New Template

= render 'form'

app/views/templates/selection.js.erb
$('#item_details').html("<%=j render 'template_items/index', template: @template if @template %>");
$('[rel~="tooltip"]').tooltip({ trigger: 'hover' });

app/views/templates/show.html.haml
- @title = @template.name
.page-header
  %h1
    = link_to @template.project.name, @template.project
    &middot;
    = link_to 'Templates', templates_path(project_id: @template.project_id)
    &middot;
    = @title
  - if current_user.all_templates.include?(@template)
    = link_to 'Edit Template', edit_template_path(@template), class: 'btn btn-xs btn-default'
    = link_to 'Delete Template', @template, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Template #{@template.name}?" }
    = link_to 'Copy Template', copy_template_path(@template), class: 'btn btn-xs btn-default'

%dl.dl-horizontal
  %dt Creator
  %dd= link_to @template.user.name, @template.user if @template.user

  %dt Avoid Weekends
  %dd= check_box_tag 'template', 'avoid_weekends', @template.avoid_weekends?, disabled: true

= render 'template_items/index', template: @template