config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'stickies#month'
  get '' => 'stickies#month', as: :dashboard

  scope module: :account do
    get :settings
    post :settings, action: :update_settings
    get :update_settings, to: redirect('settings')
    patch :change_password
    get :change_password, to: redirect('settings')
  end

  resources :comments do
    collection do
      get :search
    end
  end

  resources :boards do
    member do
      post :archive
    end
    collection do
      post :add_stickies
    end
  end

  scope module: :external do
    get :about
    get '/about/use', action: 'use', as: :about_use
    get :version
  end

  resources :groups

  resources :notifications do
    collection do
      patch :mark_all_as_read
    end
  end

  namespace :project_preferences do
    post :favorite
    post :colorpicker
    patch :update
  end

  resources :project_users do
    member do
      post :resend
    end
    collection do
      get :accept
    end
  end

  get 'invite/:invite_token' => 'project_users#invite'

  resources :projects do
    collection do
      post :selection
    end
    member do
      get :bulk
      post :reassign
    end
  end

  resources :stickies do
    collection do
      get :day
      get :week
      get :month
      get :template
    end
    member do
      post :move
      post :move_to_board
      post :complete
    end
  end

  resources :tags do
    collection do
      post :add_stickies
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :items
      post :selection
    end
    member do
      get :copy
    end
  end

  devise_for :users, path_names: { sign_up: 'join', sign_in: 'login' }, path: ''

  resources :users

  scope module: :internal do
    get :search
    post :update_task_status
    post :toggle_tag_selection
    post :toggle_owner_selection
    post :toggle_project_selection
  end

  get '/day' => 'stickies#day', as: :day
  get '/week' => 'stickies#week', as: :week
  get '/month' => 'stickies#month', as: :month
  get '/tasks' => 'stickies#tasks', as: :tasks
end

app/models/group.rb
# frozen_string_literal: true

# Allows a set of tasks to be grouped together.
class Group < ApplicationRecord
  attr_accessor :board_id, :initial_due_date

  # Concerns
  include Deletable, Filterable

  # Scopes
  scope :search, -> (arg) { where('LOWER(description) LIKE ? or groups.template_id IN (select templates.id from templates where LOWER(templates.name) LIKE ?)', arg.to_s.downcase.gsub(/^| |$/, '%'), arg.to_s.downcase.gsub(/^| |$/, '%')).references(:templates) }

  # Model Validation
  validates :project_id, presence: true

  # Model Relationships
  belongs_to :user
  belongs_to :template
  belongs_to :project
  has_many :stickies, -> { current.order(:due_date) }

  def name
    "##{id}"
  end

  def short_description(fallback = "Group #{name}")
    result = description.to_s.split(/[\r\n]/).collect(&:strip).find(&:present?)
    result = fallback unless result
    result
  end

  def short_description_second_half
    description.to_s.strip.gsub(short_description, '').strip
  end

  def destroy
    stickies.destroy_all
    super
  end
end

app/models/user.rb
# frozen_string_literal: true

# The user class provides methods to scope resources in system that the user is
# allowed to view and edit.
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable and :omniauthable
  devise :database_authenticatable, :timeoutable, # , :registerable
         :recoverable, :rememberable, :trackable, :validatable

  # TODO: Remove emailables
  EMAILABLES = [ [:sticky_creation, 'Receive email when a new task is created'],
                 [:sticky_completion, 'Receive email when a task is marked as completed'],
                 # [:sticky_due_time_changed, 'Receive email when a task\'s due date time is changed'],
                 [:sticky_comments, 'Receive email when a comment is added to a task'],
                 [:daily_stickies_due, 'Receive daily weekday emails if there are tasks due or past due'],
                 [:daily_digest, 'Receive daily digest emails of tasks that have been created and completed the previous day'] ]
  # END TODO
  CALENDAR_VIEW = [['Month View', 'month'], ['4 Week View', '4week']]

  # Concerns
  include Deletable, Searchable

  # Scopes
  scope :with_project, -> (*args) { where( "users.id in (select projects.user_id from projects where projects.id IN (?) and projects.deleted = ?) or users.id in (select project_users.user_id from project_users where project_users.project_id IN (?) and project_users.allow_editing IN (?))", args.first, false, args.first, args[1] ) }
  scope :with_name, -> (arg) { where("(users.first_name || ' ' || users.last_name) IN (?)", arg) }

  # Model Validation
  validates :first_name, :last_name, presence: true

  # Model Relationships
  has_many :comments, -> { current.order(created_at: :desc) }
  has_many :projects, -> { current.order(:name) }
  has_many :project_users
  has_many :project_preferences
  has_many :boards, -> { current }
  has_many :groups, -> { current }
  has_many :notifications, -> { joins(:project).merge(Project.current) }
  has_many :tags, -> { current }
  has_many :templates, -> { current.order(:created_at) }
  has_many :stickies, -> { current.order(:created_at) }
  has_many :owned_stickies, -> { current.order(:created_at) }, class_name: 'Sticky', foreign_key: 'owner_id'
  has_many :project_filters
  has_many :tag_filters
  has_many :owner_filters

  # User Methods

  def self.searchable_attributes
    %w(first_name last_name email)
  end

  def avatar_url(size = 80, default = 'mm')
    gravatar_id = Digest::MD5.hexdigest(self.email.to_s.downcase)
    "//gravatar.com/avatar/#{gravatar_id}.png?&s=#{size}&r=pg&d=#{default}"
  end

  def associated_users
    project_ids = all_viewable_projects.select(:id)
    User.joins('LEFT OUTER JOIN project_users ON project_users.user_id = users.id')
        .joins('LEFT OUTER JOIN projects ON projects.user_id = users.id')
        .where('project_users.project_id IN (?) or projects.id IN (?)', project_ids, project_ids)
        .distinct
  end

  def associated_users_assigned_tasks
    User.current.where(id: Sticky.where(owner_id: associated_users.select(:id), project_id: all_viewable_non_archived_projects.select(:id)).select(:owner_id))
  end

  # Overriding Devise built-in active_for_authentication? method
  def active_for_authentication?
    super && !deleted?
  end

  def unread_notifications?
    notifications.where(read: false).count > 0
  end

  def destroy
    super
    update_column :updated_at, Time.zone.now
  end

  def all_projects
    Project
      .current
      .joins("LEFT OUTER JOIN project_users ON project_users.project_id = projects.id and project_users.user_id = #{id}")
      .where('projects.user_id = ? or project_users.allow_editing = ?', id, true)
  end

  def all_non_archived_projects
    all_projects.where.not(id: project_preferences.where(archived: true).select(:project_id))
  end

  def all_viewable_projects
    Project
      .current
      .joins("LEFT OUTER JOIN project_users ON project_users.project_id = projects.id and project_users.user_id = #{id}")
      .where('projects.user_id = ? or project_users.user_id = ?', id, id)
  end

  def all_viewable_non_archived_projects
    all_viewable_projects.where.not(id: project_preferences.where(archived: true).select(:project_id))
  end

  def all_stickies
    Sticky.current.where(project_id: all_projects.select(:id)).order(created_at: :desc)
  end

  def all_stickies_due_today
    all_stickies.due_today.with_owner(id)
  end

  def all_stickies_past_due
    all_stickies.past_due.with_owner(id)
  end

  def all_stickies_due_upcoming
    all_stickies.due_upcoming.with_owner(id)
  end

  # TODO: Remove in 0.30.0
  def all_deliverable_projects
    all_digest_projects
  end
  # END TODO

  def all_deliverable_stickies_due_today
    self.all_stickies_due_today.where(project_id: self.all_deliverable_projects.collect{|p| p.id})
  end

  def all_deliverable_stickies_past_due
    self.all_stickies_past_due.where(project_id: self.all_deliverable_projects.collect{|p| p.id})
  end

  def all_deliverable_stickies_due_upcoming
    self.all_stickies_due_upcoming.where(project_id: self.all_deliverable_projects.collect{|p| p.id})
  end

  def all_digest_projects
    return Project.none unless emails_enabled?
    all_viewable_projects
      .joins("LEFT OUTER JOIN project_preferences ON project_preferences.project_id = projects.id and project_preferences.user_id = #{id}")
      .where('project_preferences.emails_enabled IS NULL or project_preferences.emails_enabled = ?', true)
  end

  # All tasks created in the last day, or over the weekend if it's Monday
  # Ex: On Monday, returns tasks created since Friday morning (Time.zone.now - 3.day)
  # Ex: On Tuesday, returns tasks created since Monday morning (Time.zone.now - 1.day)
  def digest_stickies_created
    all_stickies.where(project_id: all_digest_projects.select(:id), completed: false).where('created_at > ?', (Time.zone.now.monday? ? Time.zone.now - 3.day : Time.zone.now - 1.day))
  end

  def digest_stickies_completed
    all_stickies.where(project_id: all_digest_projects.select(:id)).where('end_date >= ?', (Date.today.monday? ? Date.today - 3.day : Date.today - 1.day))
  end

  def digest_comments
    all_viewable_comments.with_project(all_digest_projects.select(:id)).where('created_at > ?', (Time.zone.now.monday? ? Time.zone.now - 3.day : Time.zone.now - 1.day)).order(:created_at)
  end

  def all_viewable_stickies
    Sticky.current.where(project_id: all_viewable_projects.select(:id))
  end

  def all_groups
    Group.current.where(project_id: all_projects.select(:id))
  end

  def all_viewable_groups
    Group.current.where(project_id: all_viewable_projects.select(:id))
  end

  def all_boards
    Board.current.where(project_id: all_projects.select(:id))
  end

  def all_viewable_boards
    Board.current.where(project_id: all_viewable_projects.select(:id))
  end

  def all_tags
    Tag.current.where(project_id: all_projects.select(:id))
  end

  def all_viewable_tags
    Tag.current.where(project_id: all_viewable_projects.select(:id))
  end

  def all_templates
    Template.current.where(project_id: all_projects.select(:id))
  end

  def all_viewable_templates
    Template.current.where(project_id: all_viewable_projects.select(:id))
  end

  def all_comments
    comments
  end

  def all_viewable_comments
    Comment.current.where(sticky_id: all_viewable_stickies.select(:id))
  end

  def all_deletable_comments
    Comment.current.where('sticky_id IN (?) or user_id = ?', all_stickies.select(:id), id)
  end

  def name
    "#{first_name} #{last_name}"
  end

  def reverse_name
    "#{last_name}, #{first_name}"
  end

  def nickname
    "#{first_name} #{last_name.first}"
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true

# Defines a group of tasks that were created together.
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_viewable_project, only: [:index]
  before_action :find_editable_project_or_first_project, only: [:new, :create]
  before_action :set_viewable_group, only: [:show]
  before_action :set_editable_group, only: [:edit, :update, :destroy]
  before_action :redirect_without_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    @order = scrub_order(Group, params[:order], 'groups.id DESC')
    @groups = current_user.all_viewable_groups.search(params[:search]).filter(params)
                          .order(@order).page(params[:page]).per(40)
  end

  # GET /groups/1
  def show
  end

  # GET /groups/new
  def new
    if @project
      @group = @project.groups.new(group_params)
      @group.template = @project.templates.first if @project.templates.size == 1
    end

    respond_to do |format|
      format.js
      format.html { redirect_to groups_path }
    end
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.js
  def create
    g_params = group_params

    @template = @project.templates.find_by_id(params[:group][:template_id]) if @project && params[:group]

    if @template
      @group = @template.generate_stickies!(current_user, g_params[:board_id], g_params[:initial_due_date], g_params[:description])
      respond_to do |format|
        format.html { redirect_to @group, notice: @group.stickies.size.to_s + ' ' + ((@group.stickies.size == 1) ? 'sticky' : 'stickies') + " successfully created and added to #{(@board ? @board.name : 'Holding Pen')}." }
        format.js { render :create }
      end
    else
      @group = @project.groups.new(g_params) if @project
      respond_to do |format|
        format.html { redirect_to groups_path }
        format.js { render :new }
      end
    end
  end

  # PATCH /groups/1
  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private

  def set_viewable_group
    @group = current_user.all_viewable_groups.find_by_id(params[:id])
  end

  def set_editable_group
    @group = current_user.all_groups.find_by_id(params[:id])
  end

  def redirect_without_group
    empty_response_or_root_path(groups_path) unless @group
  end

  def group_params
    params[:group] ||= { blank: '1' } # {}

    if @project && params[:create_new_board] == '1'
      if params[:group_board_name].to_s.strip.blank?
        params[:group][:board_id] = nil
      else
        @board = @project.boards.where(name: params[:group_board_name].to_s.strip).first_or_create(user_id: current_user.id)
        params[:group][:board_id] = @board.id
      end
    elsif @project
      @board = @project.boards.find_by_id(params[:group][:board_id])
    end

    params[:group][:board_id] = (@board ? @board.id : nil)

    params[:group][:initial_due_date] = parse_date(params[:group][:initial_due_date], Time.zone.today)

    params.require(:group).permit(
      :description, :board_id, :template_id, :initial_due_date
    )
  end
end

app/views/groups/_board_selection.html.haml
= label_tag :group_board_id, 'Board', class: 'col-md-2 control-label'
.col-md-10
  - if @project
    - boards = @project.boards
    - board_groups = []
    - board_groups << ['Current', boards.where(archived: false).natural_sort] if boards.where(archived: false).size > 0
    - board_groups << ['Archived', boards.where(archived: true).natural_sort] if boards.where(archived: true).size > 0
    #board_id_container
      .row
        .col-xs-6.col-md-4
          = select :group, :board_id, options_for_select([['---', nil]]) + grouped_options_for_select(board_groups, @group.board_id), {}, class: 'form-control'
        .col-xs-4.col-md-2
          = link_to '+', '#', data: { object: 'create-new-board' }, class: 'btn btn-default'
    #board_name_container{ style: 'display:none' }
      .row
        .col-xs-6.col-md-4
          = hidden_field_tag :create_new_board, 0
          = text_field_tag :group_board_name, '', placeholder: 'Enter new board name', autocomplete: 'off', data: { object: 'typeahead', local: boards.pluck(:name).uniq.to_json }, class: 'form-control'
        .col-xs-4.col-md-2
          = link_to 'cancel', '#', data: { object: 'show-existing-boards' }, class: 'btn btn-default'
  - else
    = hidden_field :group, :board_id

app/views/groups/_form.html.haml
= form_for(@group, html: { class: 'form-horizontal' }) do |f|
  - if @group.errors.any?
    .callout.callout-danger
      %strong
        = pluralize @group.errors.count, 'error'
        prohibited this group from being saved

      %ul
        - @group.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :description, class: 'col-md-2 control-label'
    .col-md-10
      = f.text_area :description, rows: 7, class: 'form-control'

  .form-group
    .col-md-offset-2.col-md-10
      = f.submit nil, class: 'btn btn-primary'
      = cancel

app/views/groups/_frame_selection.html.erb
<% if @group %>
  <% boards = Frame.current.with_project(@group.project_id, current_user.id) %>
<% else %>
  <% boards = Frame.current.with_project(nil, current_user.id) %>
<% end %>
<%= label_tag :group_board_id, 'Frame', class: 'control-label' %>
<div class="controls">
  <% if @project_id %>
    <%= select_tag :group_board_id, options_for_select([['Holding Pen', nil]] + boards.order('boards.end_date desc').collect{|f| [f.project.name + ": " + f.name + ' - ' + f.short_time, f.id]}, params[:board_id] ), name: 'board_id' %>
  <% else %>
    <%= hidden_field_tag :group_board_id, nil, name: 'board_id' %>
  <% end %>
</div>

app/views/groups/_groups.html.haml
= render 'layouts/per_page', per_page: 40, object_count: @groups.total_count

%table.table.table-striped
  %thead
    %tr
      = th_sort_field @order, 'groups.id', 'Name', extra_class: 'nowrap'
      = th_sort_field @order, 'groups.template_id', 'Template', extra_class: 'nowrap'
      %th Description
      %th Tasks
      = th_sort_field @order, 'groups.project_id', 'Project', extra_class: 'nowrap'
      = th_sort_field @order, 'groups.user_id', 'Creator', extra_class: 'nowrap'
      %th Actions

  - @groups.each do |group|
    %tr
      %td= link_to group.name, group
      %td= group.template.name if group.template
      %td= group.description
      %td= group.stickies.size
      %td= link_to group.project.name, group.project
      %td= link_to group.user.name, group.user
      %td.nowrap{ style: 'vertical-align:middle' }
        - if current_user.all_groups.include?(group)
          = link_to 'Edit', edit_group_path(group), class: 'btn btn-xs btn-default'
          = link_to 'Delete', group, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Group #{group.name} and the associated #{pluralize group.stickies.size, 'Task'}?" }

.center= paginate @groups, theme: 'bootstrap'

app/views/groups/_groups_redesign.html.haml
- @project = current_user.all_viewable_projects.find_by_id(params[:project_id])
- @template = @project.templates.find_by_id(params[:template_id]) if @project

.row
  .col-md-3{ style: 'margin-bottom:20px' }
    %span{ style: 'font-weight:200;font-size:20px;' }
      = @template ? @template.name : 'No Template Selected'
      = link_to 'Edit Template', edit_template_path(@template), class: 'btn btn-xs btn-default' if @template

    %span.label.label-highlight= params[:search]
    = link_to 'clear', '#', rel: 'tooltip', title: 'Clear Filters', data: { object: 'clear-tags' }, class: 'btn btn-xs btn-default' unless params[:tag_ids].blank? && params[:search].blank?

    .list-group
      = link_to '#', data: { object: 'suppress-click' }, class: 'list-group-item list-group-heading' do
        %span.badge= @groups.total_count
        Groups
      - @groups.each do |group|
        = render 'groups/menu', group: group
    .center= paginate @groups, theme: 'bootstrap-small'

  .col-md-9{ style: 'margin-bottom:20px' }
    #group_container

app/views/groups/_inner_form.html.haml
= hidden_field_tag 'from', params[:from]

#group_template_selection_container.form-group
  = render 'groups/template_selection'

.form-group
  = f.label :initial_due_date, 'Initial Due Date', class: 'col-md-2 control-label'
  .col-md-10
    .row
      .col-md-6
        = f.text_field :initial_due_date, class: 'datepicker form-control', value: @group.initial_due_date ? @group.initial_due_date.strftime('%m/%d/%Y') : '', autocomplete: 'off'

#group_board_selection_container.form-group
  = render 'groups/board_selection'

.form-group
  = f.label :description, nil, class: 'col-md-2 control-label'
  .col-md-10
    = f.text_area :description, rows: 7, class: 'form-control'

app/views/groups/_show.html.haml
%span{ style: 'font-weight:200;font-size:20px;' }
  = @group.short_description
  = link_to 'Show Group', @group, class: 'btn btn-xs btn-default', target: '_blank'
  - if current_user.all_groups.include?(@group)
    = link_to 'Edit Group', edit_group_path(@group), class: 'btn btn-xs btn-default'
    = link_to 'Delete Group', @group, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Group #{@group.name} and the associated #{pluralize @group.stickies.size, 'Task'}?" }

= simple_format @group.short_description_second_half

.clearfix &nbsp;
= render 'stickies/list', stickies: @group.stickies
= render 'stickies/modal'

app/views/groups/_template_selection.html.haml
= label_tag :group_template_id, 'Template', class: 'col-md-2 control-label'
.col-md-10
  - if @project
    = select :group, :template_id, options_for_select([['---', nil]] + @project.templates.pluck(:name, :id), @group.template_id ), {}, class: 'form-control'
  - else
    = hidden_field :group, :template_id

app/views/groups/create.js.erb
<%# Step 1: Hide Modal %>
$('#sticky-modal-new').modal('hide');

<%# Step 2: Add Group of Tasks to View %>
<% stickies = @group.stickies %>

<% due_dates = stickies.collect(&:due_date).compact.uniq %>
<% due_dates.each do |due_date| %>
  $("#day_<%= due_date.strftime('%Y%m%d') %>").html("<%=j render 'calendar/day_body', current_date: due_date %>");
<% end %>

<% stickies.each do |sticky| %>
  list_element_with_header =      "<%=j render 'stickies/day_list',                stickies: [sticky], completed: sticky.completed, due_date: sticky.due_date %>";
  list_element =                  "<%=j render 'stickies/list_sticky_show',        sticky: sticky %>";
  addOrUpdateSticky("<%= sticky.id %>", "<%= sticky.due_date ? sticky.due_date.strftime('%Y%m%d') : 'none' %>", "<%= sticky.completed %>", list_element, list_element_with_header);
<% end %>

app/views/groups/edit.html.haml
- @title = "Edit Group #{@group.name}"

.page-header
  %h1
    - if @group.project
      = link_to @group.project.name, @group.project
      &middot;
    = link_to 'Groups', groups_path(project_id: @group.project_id)
    &middot;
    = link_to @group.name, @group
    &middot; Edit

= render 'form'

app/views/groups/index.js.erb
$('#stickies-or-templates').html("<%=j render 'groups_redesign' %>");
if($('[data-object~="group-select"]').length > 0) $('[data-object~="group-select"]').first().click();

app/views/groups/show.html.haml
- @title = @group.name
.page-header
  %h1
    = link_to @group.project.name, @group.project
    &middot;
    = link_to 'Groups', groups_path(project_id: @group.project_id)
    &middot;
    = @title
  - if current_user.all_groups.include?(@group)
    = link_to 'Edit Group', edit_group_path(@group), class: 'btn btn-xs btn-default'
    = link_to 'Delete Group', @group, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Group #{@group.name} and the associated #{pluralize @group.stickies.size, 'Task'}?" }

%dl.dl-horizontal
  %dt Creator
  %dd= link_to @group.user.name, @group.user

  %dt Generated From Template
  %dd= link_to @group.template.name, @group.template if @group.template

  %dt Description
  %dd= simple_format @group.description

#stickies
  .clearfix &nbsp;
  = render 'stickies/list', stickies: @group.stickies
  = render 'stickies/modal'

app/views/groups/show.js.erb
$("#group_container").html("<%=j render 'groups/show' %>");

app/views/groups/update.js.erb
<%# Step 1: Hide Modal %>
$('#sticky-modal-new').modal('hide');

<% stickies = @group.stickies %>

<% due_dates = (stickies.collect(&:due_date) + @all_dates).compact.uniq %>
<% due_dates.each do |due_date| %>
  $("#day_<%= due_date.strftime('%Y%m%d') %>").html("<%=j render 'calendar/day_body', current_date: due_date %>");
<% end %>

<%# Step 2: Remove existing stickies from view %>
<% stickies.each do |sticky| %>
  removeSticky("<%= sticky.id %>");
<% end %>

<%# Step 3: Add Updated Tasks to View %>
<% stickies.each do |sticky| %>
  list_element_with_header =      "<%=j render 'stickies/day_list',                stickies: [sticky], completed: sticky.completed, due_date: sticky.due_date %>";
  list_element =                  "<%=j render 'stickies/list_sticky_show',        sticky: sticky %>";
  addOrUpdateSticky("<%= sticky.id %>", "<%= sticky.due_date ? sticky.due_date.strftime('%Y%m%d') : 'none' %>", "<%= sticky.completed %>", list_element, list_element_with_header);
<% end %>