config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'stickies#month'
  get '' => 'stickies#month', as: :dashboard

  scope module: :account do
    get :settings
    post :settings, action: :update_settings
    get :update_settings, to: redirect('settings')
    patch :change_password
    get :change_password, to: redirect('settings')
  end

  resources :comments do
    collection do
      get :search
    end
  end

  resources :boards do
    member do
      post :archive
    end
    collection do
      post :add_stickies
    end
  end

  scope module: :external do
    get :about
    get '/about/use', action: 'use', as: :about_use
    get :version
  end

  resources :groups

  resources :notifications do
    collection do
      patch :mark_all_as_read
    end
  end

  namespace :project_preferences do
    post :favorite
    post :colorpicker
    patch :update
  end

  resources :project_users do
    member do
      post :resend
    end
    collection do
      get :accept
    end
  end

  get 'invite/:invite_token' => 'project_users#invite'

  resources :projects do
    collection do
      post :selection
    end
    member do
      get :bulk
      post :reassign
    end
  end

  resources :stickies do
    collection do
      get :day
      get :week
      get :month
      get :template
    end
    member do
      post :move
      post :move_to_board
      post :complete
    end
  end

  resources :tags do
    collection do
      post :add_stickies
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :items
      post :selection
    end
    member do
      get :copy
    end
  end

  devise_for :users, path_names: { sign_up: 'join', sign_in: 'login' }, path: ''

  resources :users

  scope module: :internal do
    get :search
    post :update_task_status
    post :toggle_tag_selection
    post :toggle_owner_selection
    post :toggle_project_selection
  end

  get '/day' => 'stickies#day', as: :day
  get '/week' => 'stickies#week', as: :week
  get '/month' => 'stickies#month', as: :month
  get '/tasks' => 'stickies#tasks', as: :tasks
end

app/models/project.rb
# frozen_string_literal: true

# Allows users to collaborate together to manage and complete tasks.
class Project < ApplicationRecord
  # Concerns
  include Searchable, Deletable

  # Scopes
  scope :with_user, -> (*args) { where("projects.user_id = ? or projects.id in (select project_users.project_id from project_users where project_users.user_id = ? and project_users.allow_editing IN (?))", args.first, args.first, args[1]).references(:project_users) }
  scope :has_template, -> { where('projects.id in (select DISTINCT templates.project_id from templates where templates.deleted = ?)', false) }
  scope :by_favorite, -> (arg) { joins("LEFT JOIN project_preferences ON project_preferences.project_id = projects.id and project_preferences.user_id = #{arg.to_i}") } #, order: "(project_preferences.favorite = 't') DESC"

  # Model Validation
  validates :name, :user_id, presence: true

  # Model Relationships
  belongs_to :user
  has_many :project_preferences
  has_many :project_users
  has_many :users, -> { current.order(:last_name, :first_name) }, through: :project_users
  has_many :editors, -> { current.where(project_users: { allow_editing: true }) }, through: :project_users, source: :user
  has_many :viewers, -> { current.where(project_users: { allow_editing: false }) }, through: :project_users, source: :user
  has_many :stickies, -> { current }
  has_many :boards, -> { current.order(end_date: :desc) }
  has_many :groups, -> { current }
  has_many :tags, -> { current.order(:name) }
  has_many :templates, -> { current.order(:name) }

  def self.searchable_attributes
    %w(name)
  end

  def color(current_user)
    project_preference = project_preferences.find_by_user_id(current_user.id)
    if project_preference && project_preference.color.present?
      project_preference.color
    else
      colors(Project.order(:id).pluck(:id).index(id))
    end
  end

  def text_color(current_user)
    '#fff'
  end

  # Includes Project Owner, Project Editors, and Project Viewers
  def all_members
    User.current.left_outer_joins(:projects, :project_users).where('projects.id = ? or project_users.project_id = ?', id, id).distinct
  end

  def users_to_email
    (users + [user]).uniq.select do |u|
      !u.deleted? && u.emails_enabled? && emails_enabled?(u)
    end
  end

  def editable_by?(current_user)
    modifiable_by?(current_user)
  end

  # TODO: Replace with editable_by?(current_user)
  def modifiable_by?(current_user)
    Project.current.with_user(current_user.id, true).where(id: id).count == 1
  end

  def viewable_by?(current_user)
    Project.current.with_user(current_user.id, [true, false]).where(id: id).count == 1
  end

  def sticky_count(board = 'all', filter = 'completed', user = nil)
    scope = stickies.where(completed: (filter == 'completed'))
    scope = scope.due_date_before_or_blank(Time.zone.today) if filter == 'past_due'
    scope = scope.due_date_after_or_blank(Time.zone.today) if filter == 'upcoming'
    scope = scope.where(board_id: board) if board != 'all' # Holding Pen
    scope = scope.with_owner(user.id) if user
    scope.count
  end

  def archived_by?(current_user)
    project_preference = project_preferences.find_by_user_id(current_user.id)
    project_preference.present? && project_preference.archived?
  end

  def favorited_by?(current_user)
    project_preference = project_preferences.find_by_user_id(current_user.id)
    project_preference.present? && project_preference.favorite?
  end

  def emails_enabled?(current_user)
    project_preference = project_preferences.find_by_user_id(current_user.id)
    project_preference.nil? || (project_preference.present? && project_preference.emails_enabled?)
  end

  private

  def colors(index)
    colors = %w(
      #4733e6 #7dd148 #bfbf0d #9a9cff #16a766 #4986e7 #cb74e6 #9f33e6 #ff7637
      #92e1c0 #d06c64 #9fc6e7 #c2c2c2 #fa583c #AC725E #cca6ab #b89aff #f83b22
      #43d691 #F691B2 #a67ae2 #FFAD46 #b3dc6c
    )
    colors[index.to_i % colors.size]
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

# Allows projects and related tasks to be viewed.
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_viewable_project_or_redirect, only: [:show]
  before_action :find_editable_project_or_redirect, only: [:edit, :update, :destroy, :bulk, :reassign]

  # GET /projects/1/bulk
  def bulk
  end

  # POST /projects/1/reassign
  # POST /projects/1/reassign.js
  def reassign
    original_user_id = User.with_project(@project.id, [true]).find_by_id(params[:from_user_id]).id rescue original_user_id = nil       # Editors only
    reassign_to_user_id = User.with_project(@project.id, [true]).find_by_id(params[:to_user_id]).id rescue reassign_to_user_id = nil     # Editors only
    params[:sticky_status] = 'not_completed' unless ['not_completed', 'completed', 'all'].include?(params[:sticky_status])

    sticky_scope = @project.stickies.where(owner_id: original_user_id)
    if params[:sticky_status] == 'completed'
      sticky_scope = sticky_scope.where(completed: true)
    elsif params[:sticky_status] == 'not_completed'
      sticky_scope = sticky_scope.where(completed: false)
    end
    sticky_scope = sticky_scope.with_tag(params[:tag_id]) unless params[:tag_id].blank?
    @sticky_count = sticky_scope.count

    sticky_scope.update_all(owner_id: reassign_to_user_id)

    respond_to do |format|
      format.html { redirect_to @project, notice: "#{@sticky_count} #{@sticky_count == 1 ? 'Task' : 'Tasks'} successfully reassigned." }
      format.js # reassign.js.erb
    end
  end

  def selection
    @sticky = Sticky.new(params.require(:sticky).permit(:board_id, :owner_id, { tag_ids: [] }))
    @project = current_user.all_projects.find_by_id(params[:sticky][:project_id])
  end

  # GET /projects
  def index
    @order = scrub_order(Project, params[:order], 'projects.name')
    @projects = current_user.all_viewable_projects
                            .by_favorite(current_user.id).order("(project_preferences.favorite IS NULL or project_preferences.favorite = 'f') ASC, #{@order}")
                            .page(params[:page]).per(10)
  end

  # GET /projects/1
  def show
    params[:status] ||= ['planned','completed']
    @template = @project.templates.find_by_id(params[:template_id])

    unless @template
      @board = @project.boards.find_by_name(params[:board])
      params[:board_id] = @board ? @board.id : (params[:board_id] || 'all')
      @board = @project.boards.find_by_id(params[:board_id]) unless @board
    end
  end

  # GET /projects/new
  def new
    @project = current_user.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.js
  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to(@project, notice: 'Project was successfully created.') }
        format.js do
          @sticky = current_user.stickies.new(due_date: parse_date(params[:due_date]), project_id: @project.id)
          render 'stickies/new'
        end
      else
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  # PATCH /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

  def find_viewable_project_or_redirect
    super(:id)
  end

  # Overwriting application_controller
  def find_editable_project_or_redirect
    super(:id)
  end

  def project_params
    params.require(:project).permit(
      :name, :description
    )
  end
end

app/views/projects/_board_selection.html.haml
- if @project && @project.boards.size > 0
  = label :sticky, :board_id, class: 'col-md-2 control-label'
  .col-md-10
    - if @project
      - boards = @project.boards
      - board_groups = []
      - board_groups << ['Current', boards.where(archived: false).natural_sort] if boards.where(archived: false).size > 0
      - board_groups << ['Archived', boards.where(archived: true).natural_sort] if boards.where(archived: true).size > 0
      #board_id_container
        .row
          .col-xs-6.col-md-4
            = select :sticky, :board_id, options_for_select([['---', nil]]) + grouped_options_for_select(board_groups, @sticky.board_id), {}, class: 'form-control'
          .col-xs-4.col-md-2
            = link_to '+', '#', data: { object: 'create-new-board' }, class: 'btn btn-default'
      #board_name_container{ style: 'display:none' }
        .row
          .col-xs-6.col-md-4
            = hidden_field_tag :create_new_board, 0
            = text_field_tag :sticky_board_name, '', placeholder: 'Enter new board name', autocomplete: 'off', data: { object: 'typeahead', local: boards.pluck(:name).uniq.to_json }, class: 'form-control'
          .col-xs-4.col-md-2
            = link_to 'cancel', '#', data: { object: 'show-existing-boards' }, class: 'btn btn-default'
    - else
      = hidden_field :sticky, :board_id

app/views/projects/_projects.html.haml
%table.table.table-striped
  %thead
    %tr
      %th.hidden-xs Color
      = th_sort_field @order, 'projects.name', 'Name'
      - if false
        = th_sort_field @order, 'projects.archived', 'Archived', extra_class: 'center'
        = th_sort_field @order, 'projects.favorite', 'Favorited', extra_class: 'center'
        = th_sort_field @order, 'projects.emails_enabled', 'Emails', extra_class: 'center'
      - else
        %th.center Archived
        %th.center Favorited
        %th.center Emails
      %th.hidden-xs Actions

  - @projects.each do |project|
    %tr
      %td.hidden-xs
        - form_name = "project_#{project.id}_colorpicker_form"
        = form_tag project_preferences_colorpicker_path(project_id: project), remote: true, method: :post, style: 'display:inline', id: form_name do
          = hidden_field_tag :color, project.color(current_user), id: "project_#{project.id}_hexcolor"
          .custom_widget
            .colorselector{ data: { object: 'color-selector', target: "#project_#{project.id}_hexcolor", color: project.color(current_user).to_s, form: "#project_#{project.id}_colorpicker_form" }, style: 'background-image: none' }
              %div{ id: "project_#{project.id}_hexcolor_display", style: "background-color: #{project.color(current_user)};top:0px;left:0px" }
      %td
        = link_to project.name, project, style: "color: #{project.color(current_user)}", class: "project_#{project.id}_color"
      %td.center
        - if project.archived_by?(current_user)
          %span.glyphicon.glyphicon-eye-close.text-muted
      %td.center
        - if project.favorited_by?(current_user)
          %span.glyphicon.glyphicon-star.text-warning
        - else
          %span.glyphicon.glyphicon-empty-star
      %td.center
        - if project.emails_enabled?(current_user)
          %span.glyphicon.glyphicon-envelope.text-success
      %td.nowrap.hidden-xs
        - if project.modifiable_by?(current_user)
          = link_to 'Edit', edit_project_path(project), class: 'btn btn-xs btn-default'
          = link_to 'Delete', project, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Project #{project.name}? Deleting this project will delete the project, along with all the associated tasks, boards, and comments!" }

.center= paginate @projects, theme: 'bootstrap'

app/views/projects/_reassign_dialog.html.haml
#reassign-dialog.modal{ tabindex: '-1', role: 'dialog', aria: { hidden: 'true' } }
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{ type: 'button', data: { dismiss: 'modal' }, aria: { hidden: 'true' } } &times;
        %h4.modal-title Reassign Tasks

      .modal-body
        = form_tag reassign_project_path(@project), method: :post, remote: true, class: 'form-horizontal', id: 'reassign_form' do
          - owners = User.current.with_project(@project.id, true).order('last_name, first_name')

          .form-group
            = label_tag :from_user_id, 'Currently Assigned To', class: 'col-md-3 control-label'
            .col-md-9
              = select_tag :from_user_id, options_for_select([['--Unassigned--', nil]] + owners.collect{|u| [u.reverse_name, u.id]}, params[:from_user_id]), class: 'form-control'

          .form-group
            = label_tag :to_user_id, 'Reassign To', class: 'col-md-3 control-label'
            .col-md-9
              = select_tag :to_user_id, options_for_select([['--Unassigned--', nil]] + owners.collect{|u| [u.reverse_name, u.id]}, params[:to_user_id]), class: 'form-control'

          .form-group
            = label_tag :sticky_status, 'Task status', class: 'col-md-3 control-label'
            .col-md-9
              = select_tag :sticky_status, options_for_select([['Only Not Completed', 'not_completed'], ['Only Completed', 'completed'], ['All', 'all']], params[:sticky_status]), class: 'form-control'

          .form-group
            = label_tag :tag_id, 'Only containing', class: 'col-md-3 control-label'
            .col-md-9
              = select_tag :tag_id, options_for_select([['----', nil]] + @project.tags.collect{|t| [t.name, t.id]}, params[:tag_id]), class: 'form-control'

      .modal-footer
        = link_to 'Reassign Tasks', '#', class: 'btn btn-danger-inverse', data: { target: '#reassign_form', object: 'submit', confirm: 'Are you sure you would like to reassign these tasks? This action CANNOT be reversed.' }
        = link_to 'Cancel', '#', class: 'btn btn-default', data: { target: '#reassign-dialog', object: 'modal-hide' }

app/views/projects/_tag_selection.html.haml
- if @project && @project.tags.size > 0
  .form-group
    = label :sticky, :tag_ids, 'Tags', class: 'col-md-2 control-label'
    .col-md-10
      .row
        = hidden_field_tag 'sticky[tag_ids][]', nil
        - @project.tags.each do |tag|
          .col-xs-6.col-sm-4.col-md-3.col-lg-2
            %label.checkbox.tag-checkbox{ class: "#{'tag-selected' if @sticky.tags.include?(tag)}", style: "margin-bottom: 10px;background-color:#{tag.color}" }
              = check_box_tag 'sticky[tag_ids][]', tag.id, @sticky.tags.include?(tag)
              .tag-name.nowrap{ style: 'overflow:hidden;' }
                = tag.name

app/views/projects/_user_selection.html.haml
- if @project
  - owners = [@sticky.owner, User.current.with_project(@project.id, true).order(:first_name, :last_name)].flatten.uniq.compact
- else
  - owners = [@sticky.owner, User.current.with_project(current_user.all_projects.pluck(:id), true).order(:first_name, :last_name)].flatten.uniq.compact

= label :sticky, :owner_id, 'Assigned to', class: 'col-md-2 control-label'
.col-md-10
  = select :sticky, :owner_id, options_for_select([['----', nil]] + owners.collect{|u| [u.name, u.id]}, @sticky.owner_id), {}, class: 'form-control'

app/views/projects/bulk.html.haml
- @title = 'Reassign Tasks'
.page-header
  %h1
    = link_to @project.name, @project
    &middot;
    = @title

= form_tag reassign_project_path(@project), method: :post, class: 'form-horizontal' do
  - owners = User.current.with_project(@project.id, true).order('last_name, first_name')

  .form-group
    = label_tag :from_user_id, 'Currently Assigned To', class: 'col-md-2 control-label'
    .col-md-10
      = select_tag :from_user_id, options_for_select([['--Unassigned--', nil]] + owners.collect{|u| [u.reverse_name, u.id]}, params[:from_user_id]), class: 'form-control'

  .form-group
    = label_tag :to_user_id, 'Reassign To', class: 'col-md-2 control-label'
    .col-md-10
      = select_tag :to_user_id, options_for_select([['--Unassigned--', nil]] + owners.collect{|u| [u.reverse_name, u.id]}, params[:to_user_id]), class: 'form-control'

  .form-group
    = label_tag :sticky_status, 'Task status', class: 'col-md-2 control-label'
    .col-md-10
      = select_tag :sticky_status, options_for_select([['Only Not Completed', 'not_completed'], ['Only Completed', 'completed'], ['All', 'all']], params[:sticky_status]), class: 'form-control'

  .form-group
    = label_tag :tag_id, 'Only containing', class: 'col-md-2 control-label'
    .col-md-10
      = select_tag :tag_id, options_for_select([['----', nil]] + @project.tags.collect{|t| [t.name, t.id]}, params[:tag_id]), class: 'form-control'

  .form-group
    .col-md-offset-2.col-md-10
      = submit_tag 'Reassign Tasks', class: 'btn btn-primary btn-danger-inverse', data: { confirm: 'Are you sure you would like to reassign these tasks? This action CANNOT be reversed.' }
      = link_to 'Cancel', @project, class: 'btn btn-default'

app/views/projects/edit.html.haml
- @title = "Edit Project: #{@project.name_was}"

.page-header
  %h1
    = link_to @project.name, @project
    &middot; Edit

= render 'form'

app/views/projects/index.html.haml
- @title = 'Projects'
.page-header
  %h1
    = @title
    = link_to 'Create Project', new_project_path, class: 'btn btn-primary btn-xs'
  .per-page
    = render 'layouts/per_page', per_page: 10, object_count: @projects.total_count

= render 'projects/projects'

app/views/projects/new.js.erb
$('#sticky-modal-new').find('.modal-content').html("<%=j render 'projects/new_modal' %>");
$('#sticky-modal-new').modal('show');
$("#project_name").focus();

<% @project.errors.each do |key, value| %>
  $('#project_<%= key %>').parent().parent().addClass('error');
<% end %>

resetSubmitButtons();

app/views/projects/selection.js.erb
$("#board_selection_container").html("<%=j render 'projects/board_selection' %>");
$("#owner_selection_container").html("<%=j render 'projects/user_selection' %>");
$("#tag_selection_container").html("<%=j render 'projects/tag_selection' %>");

app/views/projects/show.html.haml
- @title = "#{@project.name}"

.page-header
  %h1= @project.name

  - if @project.modifiable_by?(current_user)
    = link_to 'Edit Project', edit_project_path(@project), class: 'btn btn-default btn-xs'
    = link_to 'Delete Project', @project, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Project #{@project.name}?" }
    = link_to 'Reassign Tasks', '#', class: 'btn btn-xs btn-default', data: { object: 'modal-show', target: '#reassign-dialog' }
  %span{ id: "project_#{@project.id}_preferences" }
    = render 'project_preferences/preferences'

- status_all = (params[:status].include?('planned') && params[:status].include?('completed'))

= form_tag stickies_path(use_template: 'redesign'), method: :get, remote: true, id: "stickies_search", data: { object: "form-load#{ '-no' if @template }" } do
  = hidden_field_tag :search, params[:search]
  = hidden_field_tag :project_id, @project.id
  = hidden_field_tag :board_id, params[:board_id]
  = hidden_field_tag :tag_ids, params[:tag_ids]
  = hidden_field_tag :order, 'stickies.created_at desc'
  = hidden_field_tag :scope, params[:scope] || 'upcoming'
  = hidden_field_tag :scope_direction, params[:scope_direction] || 'forward'
  = hidden_field_tag 'assigned_to_me_hidden', '0', name: 'assigned_to_me'
  = check_box_tag 'assigned_to_me', '1', params[:assigned_to_me].to_s == '1', style: 'display:none'
  = hidden_field_tag :unassigned, '1'
  = hidden_field_tag :replace, ''

= form_tag groups_path(use_template: 'redesign'), method: :get, remote: true, id: "groups_search", data: { object: "form-load#{ '-no' unless @template }" } do
  = hidden_field_tag :group_search, params[:search], name: 'search'
  = hidden_field_tag :groups_project_id, @project.id, name: 'project_id'
  = hidden_field_tag :groups_board_id, params[:board_id], name: 'board_id'
  = hidden_field_tag :template_id, params[:template_id]
  = hidden_field_tag :group_order, 'groups.created_at desc', name: 'order'
  = hidden_field_tag :group_scope_direction, params[:scope_direction] || 'forward', name: 'scope_direction'

.row
  .col-sm-3.col-md-2
    %div{ style: 'margin-bottom:5px' }
      = text_field_tag :project_search, params[:search], name: :search, class: 'form-control'

    .row
      .col-xs-4.col-sm-12
        #unarchived_boards_container.list-group{ data: { object: 'board-archive-droppable', archived: 'false' } }
          = render 'boards/full_menu', archived: false, boards_visible: true
        #archived_boards_container.list-group{ data: { object: 'board-archive-droppable', archived: 'true' } }
          - boards_visible = (@board and @board.archived?)
          = render 'boards/full_menu', archived: true, boards_visible: boards_visible

      .col-xs-4.col-sm-12
        .list-group
          = link_to templates_path( project_id: @project.id ), class: 'list-group-item list-group-heading', rel: 'tooltip', title: 'Click to Edit Templates', data: { container: 'body' } do
            Templates
            %span.glyphicon.glyphicon-edit.pull-right
          - @project.templates.natural_sort.each do |template_name, template_id|
            = link_to template_name, project_path(@project, template_id: template_id), data: { object: 'template-select', template_id: template_id }, class: "list-group-item #{'active' if params[:template_id].to_i == template_id}"

      .col-xs-4.col-sm-12
        .list-group
          = link_to tags_path( project_id: @project.id ), class: 'list-group-item list-group-heading', rel: 'tooltip', title: 'Click to Edit Tags', data: { container: 'body' } do
            Tags
            %span.glyphicon.glyphicon-edit.pull-right
          - @project.tags.natural_sort.each do |tag_name, tag_id|
            - tag = @project.tags.find_by_id(tag_id)
            = link_to '#', data: { object: 'tag-select tag-droppable', tag_id: tag_id, project_id: @project.id }, class: "list-group-item #{'active' if params[:tag_id].to_i == tag_id}" do
              %span{ style: "background-color:#{tag.color}" } &nbsp;
              = tag_name

  #stickies-or-templates.col-sm-9.col-md-10

- unless @project.description.blank?
  .jumbotron
    = simple_markdown @project.description

#project-members= render 'project_users/index'

= render 'projects/reassign_dialog'

app/views/projects/show.js.erb
$("#stickies").html("<%=j render 'stickies/stickies' %>");

app/views/projects/show_old.html.erb
<% @title = "Project: #{@project.name}" %>
<div class="page-header">
  <h1>
    <%= @project.name %>
    <span id="project_<%= @project.id %>_favorite_link"><%= render partial: 'projects/favorite' %></span>
  </h1>
  <div class="btn-toolbar">
    <% if current_user.all_projects.include?(@project) %>
      <div class="btn-group"><%= link_to "Edit Project", edit_project_path(@project), class: 'btn btn-mini' %></div>
      <div class="btn-group"><%= link_to "Delete Project", @project, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: "Are you sure you want to delete Project #{@project.name}? Deleting this project will delete the project, along with all the associated stickies, boards, and comments!" } %></div>
    <% end %>
    <% if current_user.all_projects.include?(@project) %>

    <div class="btn-group">
      <%= link_to 'Reassign Stickies', '#', class: 'btn btn-mini', data: { object: 'modal-show', target: '#reassign-dialog' } %>
    </div>

    <div class="btn-group">
      <%= link_to "Tags", tags_path(project_id: @project.id), class: 'btn btn-mini' %>
      <button class="btn dropdown-toggle btn-mini" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Create', new_tag_path(tag: { project_id: @project.id }) %></li>
      </ul>
    </div>

    <div class="btn-group">
      <%= link_to "Templates", templates_path(project_id: @project.id), class: 'btn btn-mini' %>
      <button class="btn dropdown-toggle btn-mini" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Create', new_template_path(template: { project_id: @project.id }) %></li>
      </ul>
    </div>

    <div class="btn-group">
      <%= link_to "Boards", boards_path(project_id: @project.id), class: 'btn btn-mini' %>
      <button class="btn dropdown-toggle btn-mini" data-toggle="dropdown">
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Create', new_board_path(board: { project_id: @project.id }) %></li>
      </ul>
    </div>

    <div class="btn-group">
      <%= link_to 'Redesign', project_path(@project), class: 'btn btn-mini btn-info' %>
    </div>
  <% end %>
  </div>
</div>

<div class="row">
  <div class="span6">
    <div class="page-header">
      <h2>Details</h2>
    </div>

    <%= simple_format @project.description unless @project.description.blank? %>

    <dl class="dl-horizontal">
      <dt>Owner</dt>
      <dd><%= link_to @project.user.name, @project.user %></dd>

      <dt>Time Period</dt>
      <dd><%= @project.start_date %> to <%= @project.end_date %></dd>

      <dt>Status</dt>
      <dd><%= @project.status %></dd>
    </dl>
  </div>
  <div class="span6">
    <div class="page-header">
      <h2>
        Sticky Tags
        <%= link_to 'View Tags', tags_path(project_id: @project.id), class: 'btn btn-mini' %>
      </h2>

    </div>

    <p>
      <%= @project.tags.collect{|t| @tag = t; link_to render(partial: 'tags/show'), @tag, style: 'text-decoration:none'}.join('').html_safe %>
    </p>
  </div>
</div>

<div class="page-header">
  <h2>Sharing</h2>
</div>

<div class="row">
  <% ['editors', 'viewers'].each do |relation, allow_editing| %>
    <div class="span6">
      <% @relation = relation; @allow_editing = allow_editing %>
      <% @users = User.current.order('last_name, first_name') %>
      <p>
        <div id="<%= @relation %>_list"><%= render partial: 'project_users/index' %></div>
      </p>
    </div>
  <% end %>
</div>

<%= render partial: 'stickies/new_sticky_or_group_dialog' %>
<%= render partial: 'projects/reassign_dialog' %>

app/views/projects/visible.js.erb
$('#sticky_calendar_form').submit();