config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'stickies#month'
  get '' => 'stickies#month', as: :dashboard

  scope module: :account do
    get :settings
    post :settings, action: :update_settings
    get :update_settings, to: redirect('settings')
    patch :change_password
    get :change_password, to: redirect('settings')
  end

  resources :comments do
    collection do
      get :search
    end
  end

  resources :boards do
    member do
      post :archive
    end
    collection do
      post :add_stickies
    end
  end

  scope module: :external do
    get :about
    get '/about/use', action: 'use', as: :about_use
    get :version
  end

  resources :groups

  resources :notifications do
    collection do
      patch :mark_all_as_read
    end
  end

  namespace :project_preferences do
    post :favorite
    post :colorpicker
    patch :update
  end

  resources :project_users do
    member do
      post :resend
    end
    collection do
      get :accept
    end
  end

  get 'invite/:invite_token' => 'project_users#invite'

  resources :projects do
    collection do
      post :selection
    end
    member do
      get :bulk
      post :reassign
    end
  end

  resources :stickies do
    collection do
      get :day
      get :week
      get :month
      get :template
    end
    member do
      post :move
      post :move_to_board
      post :complete
    end
  end

  resources :tags do
    collection do
      post :add_stickies
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :items
      post :selection
    end
    member do
      get :copy
    end
  end

  devise_for :users, path_names: { sign_up: 'join', sign_in: 'login' }, path: ''

  resources :users

  scope module: :internal do
    get :search
    post :update_task_status
    post :toggle_tag_selection
    post :toggle_owner_selection
    post :toggle_project_selection
  end

  get '/day' => 'stickies#day', as: :day
  get '/week' => 'stickies#week', as: :week
  get '/month' => 'stickies#month', as: :month
  get '/tasks' => 'stickies#tasks', as: :tasks
end

app/controllers/stickies_controller.rb
# frozen_string_literal: true

# Allows tasks to be created and viewed.
class StickiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_viewable_sticky, only: [:show]
  before_action :find_editable_project_or_first_project, only: [:new, :create, :edit, :update]
  before_action :set_editable_sticky, only: [:edit, :move, :move_to_board, :complete, :update, :destroy]
  before_action :redirect_without_sticky, only: [:show, :update, :destroy]
  before_action :set_filtered_sticky_scope, only: [:day, :week, :month, :tasks, :move]

  def day
    @beginning = @anchor_date.wday == 0 ? @anchor_date : @anchor_date.beginning_of_week - 1.day
  end

  def week
    flash.delete(:notice)
    week_padding = 12
    @beginning_of_anchor_week = @anchor_date.wday == 0 ? @anchor_date : @anchor_date.beginning_of_week - 1.day
    @beginning = @beginning_of_anchor_week - week_padding.weeks
    @ending = @beginning + (2 * week_padding + 1).weeks - 1.day
    completed_dates = @stickies.with_due_date_for_calendar(@beginning, @beginning + 6.months - 1.day).where(completed: true).pluck(:due_date)
    incomplete_dates = @stickies.with_due_date_for_calendar(@beginning, @beginning + 6.months - 1.day).where(completed: false).pluck(:due_date)
    @date_count_hash = {}
    ['S','M','T','W','R','F','S'].each_with_index do |day, day_index|
      date = @beginning
      while date <= @ending
        current_date = (date + day_index.days)
        completed = completed_dates.select{|d| current_date == d.to_date }.count
        incomplete = incomplete_dates.select{|d| current_date == d.to_date }.count
        @date_count_hash[current_date.strftime("%Y%m%d")] = { completed: completed, incomplete: incomplete }
        date = date + 1.week
      end
    end
    # @max_completed_count = @date_count_hash.collect{|k,v| v[:completed]}.max || 0
    @max_incomplete_count = @date_count_hash.collect { |k,v| v[:incomplete] }.max || 0
  end

  def month
    flash.delete(:notice)
    if current_user.calendar_view == '4week'
      @start_date = @anchor_date.beginning_of_week(:sunday)
      @end_date = @start_date + 27.days
    else
      @start_date = @anchor_date.beginning_of_month
      @end_date = @anchor_date.end_of_month
    end

    @first_sunday = @start_date - @start_date.wday.day
    @last_saturday = @end_date + (6 - @end_date.wday).day
  end

  # GET /tasks
  def tasks
    @stickies = @stickies.search(params[:search])

    if params[:format] == 'csv'
      generate_csv(@stickies)
      return
    end

    @tasks = @stickies.page(params[:page]).per(40)
    render 'tasks/index'
  end

  # GET /stickies
  # GET /stickies.js
  def index
    sticky_scope = current_user.all_stickies
    sticky_scope = sticky_scope.with_owner(current_user.id) if params[:assigned_to_me] == '1'
    sticky_scope = sticky_scope.where(project_id: params[:project_id]) unless params[:project_id].blank?
    sticky_scope = sticky_scope.where.not(owner_id: nil) if params[:unassigned].to_s != '1'
    sticky_scope = sticky_scope.with_tag(params[:tag_ids].split(',')) unless params[:tag_ids].blank?
    sticky_scope = sticky_scope.with_board(params[:board_id]) unless params[:board_id].blank? or params[:board_id] == 'all'

    @order = ''

    if params[:scope].blank?
      sticky_scope = sticky_scope.where(completed: (params[:status] || []).collect{|v| (v.to_s == 'completed')})
      @order = scrub_order(Sticky, params[:order], 'completed, due_date, end_date DESC, start_date DESC')
    else
      params[:scope] = (['completed', 'past_due', 'upcoming'].include?(params[:scope]) ? params[:scope] : 'upcoming')
      case params[:scope] when 'completed'
        sticky_scope = sticky_scope.where(completed: true)
        @order = (params[:scope_direction] == 'reverse' ? "stickies.due_date NULLS FIRST" : "stickies.due_date DESC NULLS LAST")
      when 'past_due'
        sticky_scope = sticky_scope.where(completed: false).due_date_before_or_blank(Date.today)
        @order = (params[:scope_direction] == 'reverse' ? "stickies.due_date NULLS FIRST" : "stickies.due_date DESC NULLS LAST")
      when 'upcoming'
        sticky_scope = sticky_scope.where(completed: false).due_date_after_or_blank(Date.today)
        @order = (params[:scope_direction] == 'reverse' ? "(stickies.due_date IS NULL) DESC, stickies.due_date DESC" : "(stickies.due_date IS NULL) ASC, stickies.due_date ASC")
      end
    end

    sticky_scope = sticky_scope.search(params[:search]).reorder(@order)
    @stickies = sticky_scope.page(params[:page]).per(40)
    respond_to do |format|
      format.html { redirect_to tasks_path }
      format.js
    end
  end

  # GET /stickies/1
  def show
  end

  # GET /stickies/new
  def new
    if @project
      params[:sticky] ||= {}
      params[:sticky][:due_date] ||= params[:due_date]
      @sticky = @project.stickies.new(sticky_params)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /stickies/1/edit
  def edit
    respond_to do |format|
      if @sticky
        @project = @sticky.project
        format.html
        format.js
      else
        @sticky = current_user.all_viewable_stickies.find_by_id(params[:id])
        if @sticky
          format.html { redirect_to @sticky }
          format.js { render :show }
        else
          format.html { redirect_to root_path }
          format.js { head :ok }
        end
      end
    end
  end

  # POST /stickies
  # POST /stickies.js
  def create
    @sticky = @project.stickies.where(user_id: current_user.id).new(sticky_params)

    respond_to do |format|
      if @sticky.save
        @sticky.create_notifications_if_recently_completed!(current_user)
        format.html { redirect_to @sticky, notice: 'Task was successfully created.' }
        format.js
      else
        @project = @sticky.project
        format.html { render :new }
        format.js { render :new }
      end
    end
  end

  def move
    params[:due_date] = parse_date(params[:due_date])
    @all_dates = []

    if @sticky && params[:due_date].present?
      @from_date = @sticky.due_date
      @sticky.update due_date: params[:due_date]
      @to_date = @sticky.due_date
      @all_dates += [@from_date, @to_date]
      @all_dates += @sticky.shift_group((@to_date - @from_date).round, params[:shift]) if @from_date.present? && @to_date.present?
      @all_dates.compact.uniq!
    else
      @sticky = current_user.all_viewable_stickies.find_by_id(params[:id])
    end

    if @sticky
      @group = @sticky.group
      if @group
        render 'groups/update'
      else
        render 'update'
      end
    else
      head :ok
    end
  end

  def move_to_board
    @board = current_user.all_boards.find_by_id(params[:board_id])
    @original_board = @sticky.board if @sticky

    if @sticky && @board && @sticky.board != @board
      @sticky.update(board_id: @board.id)
    elsif @sticky && params[:board_id].to_s == '0' && !@sticky.board.nil?
      @sticky.update(board_id: nil)
    else
      head :ok
    end
  end

  def complete
    if @sticky
      @sticky.update completed: (params[:undo] != 'true')
      @sticky.create_notifications_if_recently_completed!(current_user)
      @all_dates = [@sticky.due_date].compact
      render :update
    else
      head :ok
    end
  end

  # PATCH /stickies/1
  # PATCH /stickies/1.js
  def update
    @from_date = @sticky.due_date

    respond_to do |format|
      if @sticky.update(sticky_params)
        @to_date = @sticky.due_date
        @all_dates = [@from_date, @to_date]
        @sticky.create_notifications_if_recently_completed!(current_user)
        @all_dates += @sticky.shift_group((@to_date - @from_date).round, params[:shift]) if @from_date.present? && @to_date.present?
        format.html { redirect_to @sticky, notice: 'Task was successfully updated.' }
        format.js
      else
        format.html { render :edit }
        format.js { render :edit }
      end
    end
  end

  # DELETE /stickies/1
  # DELETE /stickies/1.js
  def destroy
    if @sticky.group && params[:discard] == 'following'
      @sticky.group.stickies.where('due_date >= ?', @sticky.due_date).destroy_all
    elsif @sticky.group && params[:discard] == 'all'
      @sticky.group.destroy
    else # 'single'
      @sticky.destroy
    end

    respond_to do |format|
      format.html { redirect_to month_path( date: @sticky.due_date.blank? ? '' : @sticky.due_date.strftime('%Y%m%d') ), notice: 'Task was successfully deleted.' }
      format.js
    end
  end

  private

  def set_viewable_sticky
    @sticky = current_user.all_viewable_stickies.find_by_id(params[:id])
  end

  def set_editable_sticky
    @sticky = current_user.all_stickies.find_by_id(params[:id])
  end

  def redirect_without_sticky
    empty_response_or_root_path(stickies_path) unless @sticky
  end

  def sticky_params
    params[:sticky] ||= { blank: '1' }

    params[:sticky][:due_date] = parse_date(params[:sticky][:due_date]) unless params[:sticky][:due_date].blank?

    if @project && params[:create_new_board] == '1'
      if params[:sticky_board_name].to_s.strip.blank?
        params[:sticky][:board_id] = nil
      else
        @board = @project.boards.where(name: params[:sticky_board_name].to_s.strip).first_or_create(user_id: current_user.id)
        params[:sticky][:board_id] = @board.id
      end
    end

    params[:sticky][:repeat] = (Sticky::REPEAT.flatten.uniq.include?(params[:sticky][:repeat]) ? params[:sticky][:repeat] : 'none') unless params[:sticky][:repeat].blank?
    params[:sticky][:repeat_amount] = 1 if params[:sticky][:repeat] == 'none'

    params.require(:sticky).permit(
      :description, :owner_id, :board_id, :due_date, :due_time, :completed, :duration, :duration_units, :all_day, { :tag_ids => [] }, :repeat, :repeat_amount
    )
  end

  def set_filtered_sticky_scope
    @anchor_date = (Date.parse(params[:date]) rescue Date.today)

    sticky_scope = current_user.all_viewable_stickies

app/views/stickies/_edit_modal.html.haml
- @title = @sticky.new_record? ? 'New Task' : "Edit Task #{@sticky.name}"
.modal-header
  %button.close{ type: 'button', data: { dismiss: 'modal' }, aria: { hidden: 'true' } } &times;
  %h4.modal-title
    = link_to 'Projects', new_sticky_path( due_date: @sticky.due_date ? @sticky.due_date.strftime('%m/%d/%Y') : '' ), method: :get, remote: true
    &middot;
    - if @sticky.project
      = link_to @sticky.project.name, @sticky.project, target: '_blank'
      &middot;
    = @title
    - if @sticky.new_record? && @sticky.project && @sticky.project.templates.size > 0
      or
      = link_to 'Create Group', new_group_path(project_id: @sticky.project, group: { initial_due_date: @sticky.due_date ? @sticky.due_date.strftime('%m/%d/%Y') : '' }), method: :get, remote: true, class: 'btn btn-xs btn-default'

.modal-body
  = form_for(@sticky, remote: true, html: { class: 'form-horizontal', style: 'margin: 0px' }) do |f|
    = hidden_field_tag :project_id, @project.id
    = render 'stickies/inner_form', f: f

.modal-footer
  - if @sticky.new_record?
    = link_to 'Cancel', '#', class: 'btn btn-default', data: { dismiss: 'modal' }
  - else
    = link_to 'Cancel', @sticky, method: :get, remote: true, class: 'btn btn-default'

  = submit_tag @sticky.new_record? ? 'Create Task' : 'Update Task', class: 'btn btn-primary', data: { object: 'sticky-submit', target: @sticky.new_record? ? '#new_sticky' : "#edit_sticky_#{@sticky.id}" }

app/views/stickies/_inner_form.html.haml
= hidden_field_tag 'from', params[:from]

.form-group
  = f.label :description, class: 'col-md-2 control-label'
  .col-md-10
    = f.text_area :description, rows: [[7, @sticky.description.to_s.count("\n") + 1].max, 25].min, class: 'form-control', data: { object: 'expandable-text-area', default_rows: 7 }

- if @sticky.group
  .form-group
    %label.col-md-2.control-label Group Description
    .col-md-10{ style: 'padding-top:5px' }
      Group
      = link_to @sticky.group.name, @sticky.group
      = simple_format @sticky.group.description unless @sticky.group.description.blank?

#owner_selection_container.form-group
  = render 'projects/user_selection'

.form-group
  = f.label :due_date, class: 'col-md-2 control-label'
  .col-md-10
    .row
      .col-xs-6.col-md-3
        = f.text_field :due_date, class: 'datepicker form-control', value: @sticky.due_date ? @sticky.due_date.strftime('%m/%d/%Y') : '', autocomplete: 'off'
      .col-xs-6.col-md-3
        %label.checkbox{ style: 'width:185px' }
          %span.nowrap
            = f.check_box :all_day
            All day
    - if @sticky.group
      %table.blank.padded
        %tr
          %td
            = radio_button_tag 'shift', 'single', true
            %b Single:
          %td
            Only change this tasks's due date
        %tr
          %td
            = radio_button_tag 'shift', 'incomplete'
            %b Incomplete:
          %td
            Shift this tasks's due date and all incomplete tasks in group
        %tr
          %td
            = radio_button_tag 'shift', 'all'
            %b All:
          %td Shift all tasks in group

.form-group{ data: { object: 'time-options' }, style: "#{'display:none' if @sticky.all_day?}" }
  = f.label :due_time, 'Due at', class: 'col-md-2 control-label'
  .col-md-10
    .row
      .col-md-3
        = f.text_field :due_time, class: 'form-control'

.form-group{ data: { object: 'time-options' }, style: "#{'display:none' if @sticky.all_day?}" }
  = f.label :duration, nil, class: 'col-md-2 control-label'
  .col-md-10
    .row
      .col-xs-6
        = f.number_field :duration, min: 0, class: 'form-control'
      .col-xs-6
        = f.select :duration_units, options_for_select(['minutes', 'hours', 'days', 'weeks', 'months', 'years'].collect{|i| [i,i]}, @sticky.duration_units), {}, class: 'form-control'

.form-group
  = f.label :repeat, 'Repeat', class: 'col-md-2 control-label'
  .col-md-10
    .row
      .col-xs-3{ data: { object: 'repeat-options' }, style: "#{'display:none' if @sticky.repeat == 'none'}" }
        = f.number_field :repeat_amount, class: 'form-control'
      .col-xs-3
        = f.select :repeat, Sticky::REPEAT, {}, class: 'form-control'
      .col-xs-3{ style: 'line-height:30px;' }
        %span{ data: { object: 'repeat-options' }, style: "#{'display:none' if @sticky.repeat == 'none'}" } after due date
      .col-xs-3{ style: 'line-height:30px;' }
        %span{ data: { object: 'repeat-options' }, style: "#{'display:none' if @sticky.repeat == 'none'}" }
          = link_to 'Clear Repeat', '#', class: 'btn btn-xs btn-default', data: { object: 'clear-repeat' }

#board_selection_container.form-group
  = render 'projects/board_selection'

#tag_selection_container
  = render 'projects/tag_selection'

app/views/stickies/_list.html.haml
#sticky-day-lists{ data: { object: 'visible-sticky' } }
  - if stickies.count == 0
    = render 'stickies/no_tasks_found', url: defined?(url) ? url : nil
  - else
    - stickies.order(:completed, :due_date).group_by{|s| s.due_date ? [s.completed, s.due_date.to_date] : [s.completed, nil]}.each do |(completed, due_date), stickies|
      = render 'stickies/day_list', completed: completed, due_date: due_date, stickies: stickies

app/views/stickies/_list_sticky_show.html.haml
= link_to sticky, remote: true, class: "list-group-item", id: "list_sticky_#{sticky.id}", data: { object: 'sticky-draggable', sticky_id: sticky.id } do
  = image_tag sticky.owner.avatar_url(32, "identicon"), class: 'pull-right img-rounded', style: 'margin-right:-11px;margin-top: -6px;margin-bottom: -6px;' if sticky.owner
  .nowrap{ style: "overflow:hidden;#{'margin-right:37px' if sticky.owner}" }
    - if sticky.modifiable_by?(current_user)
      %span.glyphicon.regular-link{ class: "glyphicon-#{sticky.completed? ? 'check' : 'unchecked'}", data: { object: 'quick-complete', sticky_id: sticky.id.to_s, completed: "#{!sticky.completed}" } }
    - if sticky.comments.size > 0
      %span.badge= sticky.comments.size
    - sticky.tags.each do |tag|
      = render 'tags/show', tag: tag
    - unless sticky.all_day?
      %b= sticky.due_time
    = highlight(strip_tags(simple_markdown sticky.full_description), params[:search], highlighter: '<b class="label-highlight">\1</b>')
  %div{ data: { object: 'sticky-helper' }, style: 'display:none' }
    - sticky.tags.each do |tag|
      = render 'tags/show', tag: tag
    = strip_tags(simple_markdown sticky.full_description).truncate(30, separator: ' ').html_safe

app/views/stickies/_modal.html.haml
#sticky-modal-new.modal{ tabindex: '-1', role: 'dialog', aria: { hidden: 'true' } }
  .modal-dialog.modal-lg
    .modal-content

app/views/stickies/_month.html.haml
- if current_user.calendar_view == '4week'
  - move_forward = @anchor_date + 4.weeks
  - move_backward = @anchor_date - 4.weeks
- else
  - move_forward = @anchor_date + 1.month
  - move_backward = @anchor_date - 1.month

.pull-right
  = render 'calendar/filter_selection_menu'
  = succeed ' ' do
    = link_to month_path(date: move_backward.strftime('%Y%m%d'), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed]), tabindex: '-1', class: 'btn btn-xs btn-default' do
      %span.glyphicon.glyphicon-chevron-left
      %span.hidden-xs
        - if current_user.calendar_view == 'month'
          Last
          Month
  = succeed ' ' do
    = link_to month_path(date: Date.today.strftime('%Y%m%d'), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed]), tabindex: '-1', class: 'btn btn-xs btn-default', disabled: (@anchor_date == Date.today ? 'disabled' : nil) do
      %span.glyphicon.glyphicon-calendar
      %span.hidden-xs Today
  = succeed ' ' do
    = link_to month_path(date: move_forward.strftime('%Y%m%d'), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed]), tabindex: '-1', class: 'btn btn-xs btn-default' do
      %span.hidden-xs
        - if current_user.calendar_view == 'month'
          Next
          Month
      %span.glyphicon.glyphicon-chevron-right

%h4
  = Date::MONTHNAMES[@anchor_date.month]
  = @anchor_date.year

%table.month-stickies
  %thead
    %tr
      - (0..6).each do |weekday|
        %th
          = Date::ABBR_DAYNAMES[weekday]
  %tbody
    %tr
      - (0..@last_saturday - @first_sunday).each do |day_offset|
        - current_date = @first_sunday + day_offset.day
        %td.droppable{ valign: 'top', style: 'padding:0px; border: 1px solid #ddd', class: "#{'calendar-entry-body-today' if current_date == Date.today} #{'last-month' if current_date < @start_date} #{'next-month' if current_date > @end_date}", data: { due_date: current_date.strftime('%m/%d/%Y'), object: 'create-sticky', from: 'month' } }
          .calendar-entry-heading{ style: 'padding-right:2px;' }
            - if @start_date == current_date || current_date.day == 1
              - date_format = current_date.strftime '%b %e'
            - else
              - date_format = current_date.strftime '%e'
            = link_to date_format, week_path(date: current_date.strftime('%Y%m%d'), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed]), class: 'btn btn-xs', tabindex: '-1'
          %div{ style: 'min-height:90px;padding-left:2px;padding-right:2px', id: "day_#{current_date.strftime('%Y%m%d')}" }
            = render 'calendar/day_body', current_date: current_date
        = "</tr><tr>".html_safe if day_offset % 7 == 6 and day_offset != @last_saturday - @first_sunday

app/views/stickies/_no_tasks_found.html.haml
.alert.alert-warning
  %strong Heads up!
  No tasks found.
  = succeed '.' do
    = link_to 'Search across all tasks', tasks_path( tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed] ), class: ''
    - unless url.blank?
      -# TODO: Check for filter keys in params, instead of looking at the `url` variable
      or
      = link_to 'clear filters', url

app/views/stickies/calendar.js.erb
$("#month-breakdown").html("<%= escape_javascript(render("stickies/month_breakdown")) %>");

$("#calendar-title").html("<%= escape_javascript(render("calendar_title")) %>");

<% if projects = Project.where(id: @stickies.uniq.pluck(:project_id)).order(:name) and projects.size > 0 %>

  <% projects.each do |project| %>
    $(".project_<%= project.id %>_color").css('color', '<%= project.color(current_user) %>');
  <% end %>

<% end %>

activateCalendarStickyPopups();
activateCalendarDroppables();

app/views/stickies/day.html.haml
- date = @beginning
%table.day-selection
  %tr
    %td
      %div= date.strftime '%b'
      = link_to week_path( date: @anchor_date.strftime('%Y%m%d'), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed] ), class: 'btn btn-default' do
        %span.glyphicon.glyphicon-calendar
    - ['S','M','T','W','R','F','S'].each_with_index do |day, day_index|
      %td
        - date = @beginning + day_index.days
        - sticky_count = @stickies.with_due_date_for_calendar(date, date).count
        - if date.day == 1
          .nowrap
            = date.strftime '%b'
            %span{ class: "#{'btn-faded' if sticky_count == 0}" }= date.strftime '%-d'
        - else
          .nowrap{ class: "#{'btn-faded' if sticky_count == 0}" }= date.strftime '%-d'

        = link_to day_path( date: date.strftime("%Y%m%d"), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed] ), class: "btn #{date == @anchor_date ? 'btn-primary' : 'btn-default'} #{ 'btn-faded' if sticky_count == 0 }" do
          = day
    %td
      %div &nbsp;
      = link_to day_path( date: (@anchor_date + 1.week).strftime("%Y%m%d"), tags: params[:tags], owners: params[:owners], project_ids: params[:project_ids], completed: params[:completed] ), class: 'btn btn-default' do
        %span.glyphicon.glyphicon-chevron-right

- url = day_path(date: @anchor_date.strftime('%Y%m%d'))
= render 'create_and_filter_menu', url: url

.clearfix &nbsp;

= render 'list', stickies: (params[:date] == 'none' ? @stickies.where( due_date: nil ) : @stickies.with_due_date_for_calendar(@anchor_date, @anchor_date)), url: url

= render 'modal'

app/views/stickies/destroy.js.erb
$('#sticky-modal-new').modal('hide');
removeSticky("<%= @sticky.id %>");

app/views/stickies/edit.js.erb
$('#sticky-modal-new').find('.modal-content').html("<%=j render 'stickies/edit_modal' %>");
$('#sticky-modal-new').modal('show');
$("#sticky_description").focus();

typeaheadReady();
datepickerReady();

app/views/stickies/show.html.haml
- @title = "Task #{@sticky.name}"
.page-header
  %h1
    = link_to @sticky.project.name, @sticky.project
    &middot;
    = @title
    - if @sticky.completed?
      %span.glyphicon.glyphicon-check{ class: 'text-success' }
    - else
      %span.glyphicon.glyphicon-unchecked{ class: 'text-muted' }
  - if @sticky.modifiable_by?(current_user)
    = link_to 'Edit Task', edit_sticky_path(@sticky), class: 'btn btn-xs btn-default'
    - if @sticky.group
      = link_to 'Delete Task', '#', class: 'btn btn-xs btn-danger-inverse', data: { object: 'modal-show', target: "#delete-sticky-dialog_#{@sticky.id}" }
    - else
      = link_to 'Delete Task', @sticky, method: :delete, class: 'btn btn-xs btn-danger-inverse', data: { confirm: "Are you sure you want to delete Task #{@sticky.name}?" }
= render 'delete_sticky_dialog', sticky: @sticky

%dl.dl-horizontal
  %dt Description
  %dd.long-description= simple_markdown @sticky.full_description

  %dt Creator
  %dd= link_to @sticky.user.name, @sticky.user

  - if @sticky.completed? && @sticky.completer
    %dt Completed By
    %dd= link_to @sticky.completer.name, @sticky.completer

  %dt Board
  %dd= link_to @sticky.board ? @sticky.board.name : 'Holding Pen', project_path(@sticky.project, board: @sticky.board ? @sticky.board.name : nil)

  - if @sticky.owner
    %dt Assigned To
    %dd= link_to @sticky.owner.name if @sticky.owner

  - unless @sticky.due_date.blank?
    %dt Due Date
    %dd= simple_date_and_weekday @sticky.due_date

  - unless @sticky.all_day?
    %dt Due At
    %dd= @sticky.due_time

    - if @sticky.duration > 0
      %dt Duration
      %dd
        = @sticky.duration
        = @sticky.duration_units

  - if @sticky.tags.size > 0
    %dt Tags
    %dd
      - @sticky.tags.in_groups_of(4).each do |row_tags|
        .row{ style: 'margin-left:0;line-height:20px' }
          - row_tags.each_with_index do |tag, index|
            .col-md-2{ style: "#{'margin-left:0px' if index == 0}" }
              = render 'tags/show', tag: tag if tag

- if @sticky.group
  %h3
    Group
    = link_to @sticky.group.name, @sticky.group if @sticky.group
  .clearfix &nbsp;
  = render 'stickies/list', stickies: @sticky.group.stickies
  = render 'stickies/modal'

%div{ id: "sticky_#{@sticky.id}_comments" }
  = @comments = @sticky.comments.page(params[:page]); render 'comments/index'